$(function(){
	$(".midd_main_aixiu").hide();
	$(".midd_main_crm").hide();
	$(".midd_main_baiyou").hide();
	$(".midd_main_weixin").hide();
	$("#img_baiyou").hover(function(){
		$(".midd_main_baiyou").show();
		$(".midd_main_youshu").hide();
		$(".midd_main_crm").hide();
		$(".midd_main_aixiu").hide();
		$(".midd_main_weixin").hide();
	});
	$("#img_aixiu").hover(function(){
		$(".midd_main_baiyou").hide();
		$(".midd_main_youshu").hide();
		$(".midd_main_crm").hide();
		$(".midd_main_aixiu").show();
		$(".midd_main_weixin").hide();
	});
	$("#img_crm").hover(function(){
		$(".midd_main_baiyou").hide();
		$(".midd_main_youshu").hide();
		$(".midd_main_crm").show();
		$(".midd_main_aixiu").hide();
		$(".midd_main_weixin").hide();
	});
	$("#img_youshu").hover(function(){
		$(".midd_main_baiyou").hide();
		$(".midd_main_youshu").show();
		$(".midd_main_crm").hide();
		$(".midd_main_aixiu").hide();
		$(".midd_main_weixin").hide();
	});
	$("#img_weixin").hover(function(){
		$(".midd_main_baiyou").hide();
		$(".midd_main_youshu").hide();
		$(".midd_main_crm").hide();
		$(".midd_main_aixiu").hide();
		$(".midd_main_weixin").show();
	});
})